# .github/workflows/_LAUNCH TEST — gitops from PR.yml
name: _LAUNCH TEST — gitops from PR
on:
  workflow_dispatch:
    inputs:
      FRONTEND_DOCKER_TAG: { required: true, description: "Frontend tag to test" }
      BACKEND_DOCKER_TAG:  { required: true, description: "Backend tag to test" }
jobs:
  run-gitops:
    uses: Rajeshgupta123456789/travelblog-project/.github/workflows/travelblog-gitops.yml@convert-travelblog-gitops-to-actions-20251007-210855
    with:
      FRONTEND_DOCKER_TAG: ${{ inputs.FRONTEND_DOCKER_TAG }}
      BACKEND_DOCKER_TAG:  ${{ inputs.BACKEND_DOCKER_TAG }}
    secrets: inherit
