name: travelblog-gitops

on:
  workflow_dispatch:
    inputs:
      FRONTEND_DOCKER_TAG:
        required: true
        description: "Frontend Docker tag (e.g., 1.0.0)"
      BACKEND_DOCKER_TAG:
        required: true
        description: "Backend Docker tag (e.g., 1.0.0)"

permissions:
  contents: write
  pull-requests: write

env:
  # Folder and files your Jenkinsfile edited:
  GITOPS_DIR: kubernetes
  BACKEND_YAML: backend.yaml
  FRONTEND_YAML: frontend.yaml
  BACKEND_IMAGE_NAME: wanderlust-backend-beta
  FRONTEND_IMAGE_NAME: wanderlust-frontend-beta

jobs:
  Workspace_cleanup:
    name: Workspace cleanup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean untracked files (cleanWs equivalent)
        run: |
          git reset --hard
          git clean -fdx

  Git_Code_Checkout:
    name: "Git: Code Checkout"
    runs-on: ubuntu-latest
    needs: Workspace_cleanup
    steps:
      - uses: actions/checkout@v4

  Verify_Docker_Image_Tags:
    name: "Verify: Docker Image Tags"
    runs-on: ubuntu-latest
    needs: Git_Code_Checkout
    steps:
      - uses: actions/checkout@v4
      - name: Echo inputs
        run: |
          echo "FRONTEND_DOCKER_TAG=${{ inputs.FRONTEND_DOCKER_TAG }}"
          echo "BACKEND_DOCKER_TAG=${{ inputs.BACKEND_DOCKER_TAG }}"

  Update_Kubernetes_manifests:
    name: "Update: Kubernetes manifests
