name: travelblog-gitops
on:
  workflow_dispatch:
    inputs:
      FRONTEND_DOCKER_TAG:
        required: false
        description: Frontend Docker tag of the image built by the CI job
        default: ''
      BACKEND_DOCKER_TAG:
        required: false
        description: Backend Docker tag of the image built by the CI job
        default: ''
jobs:
  Workspace_cleanup:
    name: Workspace cleanup
    runs-on:
      - self-hosted
      - Node
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: cleanWs()
  Git_Code_Checkout:
    name: "Git: Code Checkout"
    runs-on:
      - self-hosted
      - Node
    needs: Workspace_cleanup
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: code_checkout("https://github.com/Rajeshgupta123456789/travelblog-project.git","main")
  Verify_Docker_Image_Tags:
    name: "Verify: Docker Image Tags"
    runs-on:
      - self-hosted
      - Node
    needs: Git_Code_Checkout
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: |-
#             echo "FRONTEND_DOCKER_TAG: ${{ inputs.FRONTEND_DOCKER_TAG }}"
#                                 echo "BACKEND_DOCKER_TAG: ${{ inputs.BACKEND_DOCKER_TAG }}"
  Update_Kubernetes_manifests:
    name: "Update: Kubernetes manifests"
    runs-on:
      - self-hosted
      - Node
    needs: Verify_Docker_Image_Tags
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: "dir('kubernetes'){\n                        sh \"\"\"\n                            sed -i -e s/wanderlust-backend-beta.*/wanderlust-backend-beta:${{ inputs.BACKEND_DOCKER_TAG }}/g backend.yaml\n                        \"\"\"\n                    }\n                    \n                    dir('kubernetes'){\n                        sh \"\"\"\n                            sed -i -e s/wanderlust-frontend-beta.*/wanderlust-frontend-beta:${{ inputs.FRONTEND_DOCKER_TAG }}/g frontend.yaml\n                        \"\"\"\n                    }"
  Git_Code_update_and_push_to_GitHub:
    name: "Git: Code update and push to GitHub"
    runs-on:
      - self-hosted
      - Node
    needs: Update_Kubernetes_manifests
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: "withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {\n                        sh '''\n                        echo \"Checking repository status: \"\n                        git status\n                    \n                        echo \"Adding changes to git: \"\n                        git add .\n                        \n                        echo \"Commiting changes: \"\n                        git commit -m \"Updated environment variables\"\n                        \n                        echo \"Pushing changes to github: \"\n                        git push https://github.com/Rajeshgupta123456789/travelblog-project.git main\n                    '''\n                    }"
  Post-Build:
    if: always()
    name: Post Build
    runs-on:
      - self-hosted
      - Node
    needs:
    - Workspace_cleanup
    - Git_Code_Checkout
    - Verify_Docker_Image_Tags
    - Update_Kubernetes_manifests
    - Git_Code_update_and_push_to_GitHub
    steps:
    - name: snapshot post build workflow status
      run: |-
        echo "success=${{ contains(needs.*.result,'success') && !contains(needs.*.result,'cancelled') && !contains(needs.*.result,'failure') }}" >> $GITHUB_OUTPUT
        echo "failure=${{ contains(needs.*.result,'failure') && !contains(needs.*.result,'cancelled') }}" >> $GITHUB_OUTPUT
      id: post_build
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: |-
#             emailext attachLog: true,
#                             from: 'ankitgup.05@gmail.com',
#                             subject: "Wanderlust Application build failed - '${currentBuild.result}'",
#                             body: """
#                                 <html>
#                                 <body>
#                                     <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
#                                         <p style="color: black; font-weight: bold;">Project: ${{ env.JOB_NAME }}</p>
#                                     </div>
#                                     <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
#                                         <p style="color: black; font-weight: bold;">Build Number: ${{ env.BUILD_NUMBER }}</p>
#                                     </div>
#                                 </body>
#                                 </html>
#                         """,
#                         to: 'ankitgup.05@gmail.com',
#                         mimeType: 'text/html'
#       if: steps.post_build.outputs.failure == 'true'
#     # 'script' was not transformed because there is no suitable equivalent in GitHub Actions
#     - name: script
#       arguments:
#       - key: scriptBlock
#         value:
#           isLiteral: true
#           value: |-
#             emailext attachLog: true,
#                             from: 'ankitgup.05@gmail.com',
#                             subject: "Wanderlust Application has been updated and deployed - '${currentBuild.result}'",
#                             body: """
#                                 <html>
#                                 <body>
#                                     <div style="background-color: #FFA07A; padding: 10px; margin-bottom: 10px;">
#                                         <p style="color: black; font-weight: bold;">Project: ${{ env.JOB_NAME }}</p>
#                                     </div>
#                                     <div style="background-color: #90EE90; padding: 10px; margin-bottom: 10px;">
#                                         <p style="color: black; font-weight: bold;">Build Number: ${{ env.BUILD_NUMBER }}</p>
#                                     </div>
#                                     <div style="background-color: #87CEEB; padding: 10px; margin-bottom: 10px;">
#                                         <p style="color: black; font-weight: bold;">URL: ${{ env.BUILD_URL }}</p>
#                                     </div>
#                                 </body>
#                                 </html>
#                         """,
#                         to: 'ankitgup.05@gmail.com',
#                         mimeType: 'text/html'
#       if: steps.post_build.outputs.success == 'true'
